replicaCount: 1

namespace: minikube

service:
  port: 8094
  type: ClusterIP

ingress:
  enabled: false
  host: rops.example.com
  certName: frontstage-cert

networkPolicy:
  egress: |
    - {}
  ingress: |
    - {}

resources:
  requests:
    memory: "256Mi"