replicaCount: 1

env: "minikube"

image:
  tag: 191219

uaa:
  client_id: a-client-id
  client_secret: supersecret

service:
  port: 8094
  type: NodePort

resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"