language: python
sudo: required
dist: trusty
python: '3.6'

cache:
  - pip

env:
  - APP_SETTINGS=TestingConfig

install:
  - pip install pipenv==8.3.2
  - pipenv install --dev --deploy

script:
  - pipenv run python run_tests.py
  - pipenv check --style . --max-line-length 160

after_success:
  - pipenv run codecov

branches:
  only:
    - master
