language: python
sudo: required
dist: trusty
python: '3.6'
node: '10'

cache:
  - pip

env:
   global:
     - APP_SETTINGS=TestingConfig
     - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - npm install
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make test

after_success:
  - pipenv run codecov

branches:
  only:
    - master
