language: python
sudo: required
dist: trusty
python: '3.6'

cache:
  - pip

env:
  - APP_SETTINGS=TestingConfig

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv check --style . --max-line-length 120
  - pipenv run python run_tests.py

after_success:
  - pipenv run codecov

branches:
  only:
    - master
