env: minikube
namespace: minikube
publicIP: false

sendEmailToGovNotify: false

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

admin:
  createAccountPassword: password
  createccountEmailExpiry: "3628800"

analytics:
  enabled: false

gcp:
  project: ras-rm-sandbox
  topic: ras-rm-notify-test

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "256Mi"

ingress:
  enabled: false
  timeoutSec: 60
  gcpHost: rops-gcp.example.com
  gcpCertName: response-operations-gcp-cert

uaa:
  client_id: response_operations
  client_secret: password

notify:
  confirmCreateAccountTemplate: confirm_create_account_id
  confirmPasswordChangeTemplate: confirm_password_change_id
  requestCreateAccountTemplate: request_create_account_id
  requestPasswordChangeTemplate: request_password_change_id

dashboard:
  hasIngress: false
  address: https://dashboard.example.com

database:
   managedRedis: false

dns:
  enabled: false
  wellKnownPort: 8080

test:
  enabled: false

sample:
  file:
    uploader:
      enabled: false

canary:
  enabled: true
  name: canary