env: minikube
namespace: minikube
publicIP: false

sendEmailToGovNotify: false

admin:
  createAccountEmailExpiry: "2419200"
  updateAccountEmailExpiry: "259200"
  completeToNotStartedWaitTime: "1200"

analytics:
  enabled: false

gcp:
  project: ras-rm-sandbox
  topic: ras-rm-notify-test

scheme: http

image:
  devRepo: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  name: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "250Mi"
    cpu: "100m"
  limits:
    cpu: "300m"
    memory: "300Mi"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 200
  cpuPercentage: 200
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

ingress:
  enabled: false
  timeoutSec: 60
  gcpHost: rops-gcp.example.com
  gcpCertName: response-operations-gcp-cert

notify:
  createUserAccountTemplate: create_user_account_id
  confirmPasswordChangeTemplate: confirm_password_change_id
  requestPasswordChangeTemplate: request_password_change_id
  updateAccountDetailsTemplate: update_account_details_id
  updateAccountEmailTemplate: update_email_id
  updateAccountPasswordTemplate: update_account_password_id
  updateUserPermissionsTemplate: update_user_permissions_id
  deleteUserTemplate: delete_user_id
  
cir:
  enabled: false  
  
dashboard:
  hasIngress: false
  address: https://dashboard.example.com

database:
   managedRedis: false

dns:
  enabled: false
  wellKnownPort: 8080

test:
  enabled: false
