replicaCount: 1

namespace: minikube

container:
  port: 80

service:
  port: 80
  type: ClusterIP

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always

ingress:
  enabled: false
  host: rops.example.com
  certName: frontstage-cert

uaa:
  client_id: response_operations
  client_secret: password

networkPolicy:
  egress: |
    - {}
  ingress: |
    - {}

resources:
  requests:
    memory: "256Mi"