env: minikube
namespace: minikube
publicIP: false

sendEmailToGovNotify: false

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

admin:
  createAccountPassword: password
  createccountEmailExpiry: "3628800"

analytics:
  enabled: false

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always

container:
  port: 8080
service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "256Mi"

ingress:
  enabled: false
  host: rops.example.com
  certName: response-operations-cert

uaa:
  client_id: response_operations
  client_secret: password

notify:
  confirmCreateAccountTemplate: confirm_create_account_id
  confirmPasswordChangeTemplate: confirm_password_change_id
  requestCreateAccountTemplate: request_create_account_id
  requestPasswordChangeTemplate: request_password_change_id

database:
   managedRedis: false

networkPolicy:
  egress: |
    - {}
  ingress: |
    - {}
