env: minikube
namespace: minikube
publicIP: false

sendEmailToGovNotify: false

admin:
  createAccountEmailExpiry: "3628800"

analytics:
  enabled: false

gcp:
  project: ras-rm-sandbox
  topic: ras-rm-notify-test

scheme: http

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "250Mi"
    cpu: "100m"
  limits:
    cpu: "300m"
    memory: "300Mi"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 200
  cpuPercentage: 200
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

ingress:
  enabled: false
  timeoutSec: 60
  gcpHost: rops-gcp.example.com
  gcpCertName: response-operations-gcp-cert

notify:
  confirmCreateAccountTemplate: confirm_create_account_id
  confirmPasswordChangeTemplate: confirm_password_change_id
  requestCreateAccountTemplate: request_create_account_id
  requestPasswordChangeTemplate: request_password_change_id
  changeAccountNameTemplate: change_account_name_id
  
dashboard:
  hasIngress: false
  address: https://dashboard.example.com

database:
   managedRedis: false

dns:
  enabled: false
  wellKnownPort: 8080

test:
  enabled: false
  
features:
  v3Enabled: true

