replicaCount: 1

namespace: minikube

container:
  port: 80

service:
  port: 80
  type: ClusterIP

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always

databaseConfig: |
  - name: DB_HOST
    value: $(POSTGRES_SERVICE_HOST)
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: db-config
        key: db-port
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-config
        key: db-name
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: password

ingress:
  enabled: false
  host: rops.example.com
  certName: frontstage-cert

uaa:
  client_id: response_operations
  client_secret: password

networkPolicy:
  egress: |
    - {}
  ingress: |
    - {}

resources:
  requests:
    memory: "256Mi"