{{- if .Values.publicIP }}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: rops-backend-config
spec:
  securityPolicy:
    name: "ras-cloud-armour-policy"
  customRequestHeaders:
    X-Forwarded-Proto: https
  sessionAffinity: ClientIP
{{- end }}
