apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: rops
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: rops
      name: create-account-password
      version: latest
      property: create-account-password
    - key: rops
      name: client-id
      version: latest
      property: client-id
    - key: rops
      name: client-secret
      version: latest
      property: client-secret