name: comment

on:
  push:
    branches: [ main ]

env:
  SERVICE: response-operations-ui

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: Authenticate with Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCR_KEY }}'
          
      - uses: onsdigital/ras-rm-spinnaker-action@main
        with:
          comment-body: '/deploy babbal'
          gcp-project: ${{ secrets.GOOGLE_PROJECT_ID }}
          bot-token: ${{ secrets.BOT_TOKEN }}
          spinnaker-topic: ${{ secrets.SPINNAKER_TOPIC }}
          artifact-bucket: ${{ secrets.ARTIFACT_BUCKET }}
          helm-chart: ${{ env.SERVICE }}/${{ env.SERVICE }}-latest.tgz


