name: comment

on:
  push:
    branches: [ main ]

env:
  SERVICE: response-operations-ui

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
      with:
        repository: 'onsdigital/ras-rm-spinnaker-action@main'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCR_KEY }}'


